/* md5: 6f1f9b4c8e294f40f1caa473021faa3c */
/* Rap repository id: 308 */
/* @infra/generation version: 3.0.1-beta.2 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: /repository/editor?id=308
 */

import {
  createHttpRequest,
  createFallbackFetch,
  createSeprateInterceptor,
} from '@rapper/request'
import { IModels } from './models'
import { POS_MAP } from './pos'

export const http = createHttpRequest<IModels>({
  baseURL:
    process.env.NODE_ENV === 'production'
      ? ''
      : '/api/app/mock/308',
})

http.interceptors.request.use((config) => {
  const url = [
    (config.baseURL || '').replace(/\/$/, ''),
    '/api/qqq'.replace(/^\//, ''),
  ].join('/')
  config.baseURL = url
  return config
})

http.interceptors.request.use(createSeprateInterceptor(POS_MAP))

export const fetch = createFallbackFetch<IModels>(http)

export default http
