/* md5: 70ea4799a0660d9f70e529f7c4a94a24 */
/* Rap repository id: 308 */
/* @infra/generation version: 3.0.1-beta.2 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: /repository/editor?id=308
 */

import { IModels } from './models'

export type Models = IModels
export * from './http'
export * from './models'
