/* md5: f803f14084421e692744adaba4a5f0e1 */
/* Rap repository id: 308 */
/* @infra/generation version: 3.0.1-beta.2 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

/**
 * This file is automatically generated by Rapper to synchronize the Rap platform interface, please do not modify
 * Rap repository url: /repository/editor?id=308
 */

import { createUseHttp } from '@rapper3/react-ahooks'
import { http } from './http'
import { IModels } from './models'

export const useHttp = createUseHttp<IModels>(http)
export const useFetch = useHttp
